import os as OS
import datetime as Datetime


class Path:
    BaseDir = OS.path.dirname(OS.path.abspath(__file__))
    RootDir = OS.path.abspath(OS.path.join(BaseDir, "..", ".."))
    StaticDir = OS.path.join(RootDir, "Static")
    CSSDir = OS.path.join(StaticDir, "CSS")
    JSDir = OS.path.join(StaticDir, "JS")
    TemplatesDir = OS.path.join(RootDir, "Code", "Templates")
    AdminTemplatesDir = OS.path.join(TemplatesDir, "Admin")
    ClientTemplatesDir = OS.path.join(TemplatesDir, "Client")
    GlobalTemplatesDir = OS.path.join(TemplatesDir, "Global")
    UploadsDir = OS.path.join(StaticDir, "Uploads")
    ImagesDir = OS.path.join(StaticDir, "Images")
    ReceiptsDir = OS.path.join(UploadsDir, "Receipts")
    NewsDir = OS.path.join(UploadsDir, "News")
    GalleryDir = OS.path.join(ImagesDir, "Gallery")
    CommitteeDir = OS.path.join(ImagesDir, "Committee")
    TechnicalCommitteeDir = OS.path.join(ImagesDir, "TechnicalCommittee")
    DatabaseDir = OS.path.join(StaticDir, "DataBase")
    DataBase = OS.path.join(DatabaseDir, "Airocup.db")
    GuideLineDir = OS.path.join(DatabaseDir, "GuideLine", "Guideline.pdf")

    class URLs:
        CSS_Style = "CSS/Style.css"
        CSS_Admin = "CSS/Admin.css"

        JS_Main = "JS/Main.js"
        JS_Admin = "JS/Admin.js"

        class Images:
            Logo = "Images/Logo/"
            Gallery = "Images/Gallery/"
            Committee = "Images/Committee/"
            TechnicalCommittee = "Images/TechnicalCommittee/"
            Poster = "Images/Poster/"
            Sponsors = "Images/Logo/Sponsors/"

        class Files:
            Poster = "Images/Poster/Poster.png"
            GuideLine = "DataBase/GuideLine/Guideline.pdf"
            SiteWebManifest = "site.webmanifest"

    SolidLogos = {
        "MainFest 512": "Images/Logo/Solid/Airocup Logo MainFest 512.png",
        "SolidPurpleGlowCrop": "Images/Logo/Solid/SPG Airocup Logo Crop.png",
        "SolidPurpleGlow": "Images/Logo/Solid/SPG Airocup Logo.png",
        "SolidWhite": "Images/Logo/Solid/SW Airocup Logo.png",
        "SolidWhiteFavicon": "Images/Logo/Solid/SWF Airocup Logo.ico",
    }

    TransparentLogos = {
        "TransparentBlack": "Images/Logo/Transparent/TB Airocup Logo.png",
        "TransparentPurple": "Images/Logo/Transparent/TP Airocup Logo.png",
        "TransparentWhite": "Images/Logo/Transparent/TW Airocup Logo.png",
    }

    SponsorsLogos = {
        "EducationMinistry": "Images/Logo/Sponsors/Amoozsh Parvarsh.png",
        "InteriorMinistry": "Images/Logo/Sponsors/Ministry Of The Interior Of Iran.png",
        "StudentResearchCenter": "Images/Logo/Sponsors/Student Research Center.png",
        "StudentResearchCenterTehran": "Images/Logo/Sponsors/Student Research Center Tehran.png",
        "ScienceMinistry": "Images/Logo/Sponsors/Ministry Of Science And Technology.png",
        "EducationDepartmentTehran": "Images/Logo/Sponsors/Education Department Tehran.png",
        "University": "Images/Logo/Sponsors/University Logo.png",
        "WaterWaste": "Images/Logo/Sponsors/Water And Waste.png",
    }


EducationLevels = {
    "ابتدایی": {"grades": (1, 6), "ages": (6, 12)},
    "متوسطه اول": {"grades": (7, 9), "ages": (13, 16)},
    "متوسطه دوم": {"grades": (10, 12), "ages": (16, 18)},
    "دانشجویی": {"grades": None, "ages": (19, 60)},
    "آزاد": {"grades": None, "ages": (18, 65)},
}

AllowedEducation = set(EducationLevels.keys())


class ForbiddenContent:  # todo
    WORDS = {
        "Admin",
        "Administrator",
        "mod",
        "sex",
        "boobs",
        "penis",
        "moderator",
        "root",
        "spam",
        "free",
        "money",
        "win",
        "idiot",
        "stupid",
        "fool",
        "ادمین",
        "مدیر",
        "پشتیبان",
        "رایگان",
        "جایزه",
        "برنده",
        "احمق",
        "نادان",
        "ابله",
    }


class Event:
    StartDate = "2024-12-01"
    EndDate = "2024-12-05"
    StageOne = "مجازی (لیگ ۲ ۳٬ ۴٬ ۵٬)"
    StageTwo = "حضوری در دانشگاه علم و صنعت، بهمن‌ماه ۱۴۰۴"
    RegistrationDeadline = "مهلت تا ۳۰ آبان"

class Location:
    Address = "دانشگاه علم و صنعت ایران، تهران، ایران"
    GoogleMapURL = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3238.3677491108874!2d51.50446664881416!3d35.74176489774458!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3f8e032fd49e3809%3A0x470e49fef97ae303!2sIran%20University%20of%20Science%20and%20Technology%20(IUST)!5e0!3m2!1sen!2s!4v1759235497853!5m2!1sen!2s"


class Date:
    DaysInMonth = {
        1: 31,
        2: 31,
        3: 31,
        4: 31,
        5: 31,
        6: 31,
        7: 30,
        8: 30,
        9: 30,
        10: 30,
        11: 30,
        12: 29,
    }
    PersianMonths = {
        1: "فروردین",
        2: "اردیبهشت",
        3: "خرداد",
        4: "تیر",
        5: "مرداد",
        6: "شهریور",
        7: "مهر",
        8: "آبان",
        9: "آذر",
        10: "دی",
        11: "بهمن",
        12: "اسفند",
    }

    @staticmethod
    def GetAllowedYears():
        CurrentYear = Datetime.datetime.now(Datetime.timezone.utc).year
        return list(range(CurrentYear - 80, CurrentYear - 4))


class AppConfig:
    MaxTeamPerClient = 20
    MaxMembersPerTeam = 10
    MaxImageSize = 50 * 1024 * 1024
    MaxDocumentSize = 100 * 1024 * 1024
    MaxVideoSize = 300 * 1024 * 1024
    AllowedExtensions = [
        "png",
        "jpg",
        "jpeg",
        "gif",
        "pdf",
        "docx",
        "doc",
        "xlsx",
        "xls",
        "ppt",
        "pptx",
        "mp4",
        "mov",
        "avi",
        "mkv",
        "webm",
    ]
    AllowedMimeTypes = [
        "image/jpeg",
        "image/png",
        "image/gif",
        "application/pdf",
        "application/msword",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "application/vnd.ms-excel",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "application/vnd.ms-powerpoint",
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "video/mp4",
        "video/quicktime",
        "video/x-msvideo",
        "video/x-matroska",
        "video/webm",
    ]


class Contact:
    Phone = "09352117339"
    EmailPrimary = "airocupiran@gmail.com"
    EmailSecondary = "ai90maharat@gmail.com"
    Website = "https://airocup.org"
    Instagram = "@airo.cup"
    LinkedIn = "linkedin.com/in/airo-cup-آیروکاپ-5b4818231"
    Bale = "https://ble.ir/join/8VwzjR1U3f"
    AparatChannel = "https://www.aparat.com/Kia_coder"
    AparatPlaylist = "https://www.aparat.com/playlist/22114839"
    AparatEmbedURL = (
        "https://www.aparat.com/video/video/embed/videohash/wtw75xo/vt/frame"
    )


ContactPointsData = [
    {
        "href": f"tel:{Contact.Phone}",
        "icon": "fas fa-phone-alt",
        "label": "پشتیبانی (تلفنی)",
        "display": Contact.Phone,
        "target": None,
    },
    {
        "href": f"mailto:{Contact.EmailPrimary}",
        "icon": "fas fa-envelope",
        "label": "ایمیل اصلی (سازمانی)",
        "display": Contact.EmailPrimary,
        "target": None,
    },
    {
        "href": f"mailto:{Contact.EmailSecondary}",
        "icon": "fas fa-envelope-open-text",
        "label": "ایمیل دوم (پشتیبانی)",
        "display": Contact.EmailSecondary,
        "target": None,
    },
    {
        "href": Contact.Bale,
        "icon": "fas fa-comment-dots",
        "label": "کانال بله",
        "display": "@airocup2025",
        "target": "_blank",
    },
    {
        "href": f"https://instagram.com/{Contact.Instagram.replace('@', '')}",
        "icon": "fab fa-instagram",
        "label": "اینستاگرام",
        "display": Contact.Instagram,
        "target": "_blank",
    },
    {
        "href": f"https://{Contact.LinkedIn}",
        "icon": "fab fa-linkedin",
        "label": "لینکدین",
        "display": "Airocup LinkedIn",
        "target": "_blank",
    },
    {
        "href": Contact.AparatPlaylist,
        "icon": "fas fa-play-circle",
        "label": "آپارات",
        "display": "کانال آپارات آیروکاپ",
        "target": "_blank",
    },
]

ProvincesData = {
    "آذربایجان شرقی": [
        "تبریز",
        "مراغه",
        "مرند",
        "اهر",
        "میانه",
        "بناب",
        "سراب",
        "آذرشهر",
        "هادیشهر",
        "عجب‌شیر",
        "اسکو",
        "ایلخچی",
        "باسمنج",
        "بستان‌آباد",
        "شبستر",
        "کلیبر",
        "ورزقان",
        "هریس",
        "هوراند",
        "خداآفرین",
        "جلفا",
        "چاراویماق",
        "صوفیان",
        "تسوج",
        "خامنه",
        "سیس",
        "شربیان",
        "شرفخانه",
        "شندآباد",
        "صایین‌قلعه",
    ],
    "آذربایجان غربی": [
        "ارومیه",
        "خوی",
        "مهاباد",
        "بوکان",
        "میاندوآب",
        "سلماس",
        "پیرانشهر",
        "نقده",
        "سردشت",
        "شاهین‌دژ",
        "اشنویه",
        "تکاب",
        "چالدران",
        "پلدشت",
        "سیه‌چشمه",
        "قوشچی",
        "محمدیار",
        "ربط",
        "سرو",
        "دیزج",
        "فیرورق",
        "نالوس",
    ],
    "اردبیل": [
        "اردبیل",
        "پارس‌آباد",
        "مشگین‌شهر",
        "خلخال",
        "گرمی",
        "بیله‌سوار",
        "نمین",
        "جعفرآباد",
        "کوثر",
        "نیر",
        "سرعین",
        "گیوی",
        "لاهرود",
        "انگوت",
        "تازه‌کند",
        "جعفرآباد",
        "قصابه",
        "مرادلو",
        "هشتجین",
    ],
    "اصفهان": [
        "اصفهان",
        "کاشان",
        "خمینی‌شهر",
        "نجف‌آباد",
        "شاهین‌شهر",
        "شهرضا",
        "فولادشهر",
        "مبارکه",
        "آران و بیدگل",
        "گلپایگان",
        "خوانسار",
        "سمیرم",
        "درچه",
        "زرین‌شهر",
        "دامنه",
        "برخوار",
        "چادگان",
        "خور و بیابانک",
        "تیران و کرون",
        "فلاورجان",
        "نطنز",
        "نائین",
    ],
    "البرز": [
        "کرج",
        "هشتگرد",
        "نظرآباد",
        "محمدشهر",
        "فردیس",
        "کمال‌شهر",
        "ماهدشت",
        "مشکین‌دشت",
        "چهارباغ",
        "گرمدره",
        "گلسار",
        "اشترجان",
        "پلنگ‌آباد",
        "تنکمان",
        "عشق‌آباد",
        "کوهپایه",
    ],
    "ایلام": [
        "ایلام",
        "دهلران",
        "ایوان",
        "آبدانان",
        "دره‌شهر",
        "مهران",
        "سرابله",
        "ارکواز",
        "چوار",
        "آسمان‌آباد",
        "بدره",
        "پهله",
        "توحید",
        "زرنه",
        "لومار",
        "مورموری",
    ],
    "بوشهر": [
        "بوشهر",
        "برازجان",
        "گناوه",
        "کنگان",
        "خورموج",
        "جم",
        "عسلویه",
        "دیر",
        "دیلم",
        "اهرم",
        "سیراف",
        "چغادک",
        "دلوار",
        "شنبه",
        "کاکی",
        "وحدتیه",
    ],
    "تهران": [
        "تهران",
        "شهریار",
        "اسلام‌شهر",
        "قدس",
        "ملارد",
        "ورامین",
        "پاکدشت",
        "قرچک",
        "اندیشه",
        "رباط‌کریم",
        "ری",
        "شهرقدس",
        "فشم",
        "کهریزک",
        "لواسان",
        "نسیم‌شهر",
        "پردیس",
        "بومهن",
        "جاجرود",
        "دماوند",
        "فیروزکوه",
    ],
    "چهارمحال و بختیاری": [
        "شهرکرد",
        "بروجن",
        "فرخ‌شهر",
        "فارسان",
        "لردگان",
        "هفشجان",
        "جونقان",
        "سامان",
        "فرادنبه",
        "دستنا",
        "بن",
        "سودجان",
        "شلمزار",
        "گهرو",
        "نافچ",
        "وردنجان",
        "کیان",
        "مال خلیفه",
        "نقنه",
    ],
    "خراسان جنوبی": [
        "بیرجند",
        "قائن",
        "فردوس",
        "نهبندان",
        "طبس",
        "سربیشه",
        "سرایان",
        "بشرویه",
        "درمیان",
        "خوسف",
        "زیرکوه",
        "اسدیه",
        "اسفدن",
        "آیسک",
        "حاجی‌آباد",
        "خضری",
        "دشت بیاض",
        "سه‌قلعه",
        "مود",
    ],
    "خراسان رضوی": [
        "مشهد",
        "نیشابور",
        "سبزوار",
        "تربت حیدریه",
        "کاشمر",
        "قوچان",
        "تربت جام",
        "تایباد",
        "چناران",
        "سرخس",
        "فریمان",
        "بردسکن",
        "گناباد",
        "درگز",
        "خواف",
        "سلامی",
        "شاندیز",
        "طرقبه",
        "کلات",
        "رشتخوار",
        "فیض‌آباد",
    ],
    "خراسان شمالی": [
        "بجنورد",
        "شیروان",
        "اسفراین",
        "آشخانه",
        "جاجرم",
        "فاروج",
        "گرمه",
        "ساروج",
        "قاضی",
        "پیش قلعه",
        "حصارگرمخان",
        "درق",
        "راز",
        "سنخواست",
        "شوقان",
        "لوجلی",
    ],
    "خوزستان": [
        "اهواز",
        "دزفول",
        "آبادان",
        "ماهشهر",
        "اندیمشک",
        "خرمشهر",
        "ایذه",
        "شوشتر",
        "مسجدسلیمان",
        "بهبهان",
        "شوش",
        "رامهرمز",
        "بندرماهشهر",
        "هویزه",
        "حمیدیه",
        "لالی",
        "اندیکا",
        "آغاجاری",
        "باغ‌ملک",
        "هفتگل",
        "رامشیر",
        "کارون",
    ],
    "زنجان": [
        "زنجان",
        "ابهر",
        "خرمدره",
        "قیدار",
        "هیدج",
        "صائین‌قلعه",
        "آب‌بر",
        "سلطانیه",
        "ماهنشان",
        "زرین‌رود",
        "چورزق",
        "دندی",
        "سجاس",
        "کرسف",
        "نیک‌پی",
        "حلب",
        "ارمغانخانه",
    ],
    "سمنان": [
        "سمنان",
        "شاهرود",
        "دامغان",
        "گرمسار",
        "مهدی‌شهر",
        "ایوانکی",
        "شهمیرزاد",
        "آرادان",
        "بیارجمند",
        "دیباج",
        "رودیان",
        "سرخه",
        "کلاته",
        "کهن‌آباد",
        "مجن",
        "مهمانسرا",
    ],
    "سیستان و بلوچستان": [
        "زاهدان",
        "زابل",
        "ایرانشهر",
        "چابهار",
        "سراوان",
        "خاش",
        "کنارک",
        "جالق",
        "سرباز",
        "نیک‌شهر",
        "میرجاوه",
        "بمپور",
        "پیشین",
        "راسک",
        "سوران",
        "فنوج",
        "قصرقند",
        "محمدان",
        "هیدوج",
    ],
    "فارس": [
        "شیراز",
        "کازرون",
        "جهرم",
        "مرودشت",
        "فسا",
        "داراب",
        "لار",
        "آباده",
        "نورآباد",
        "اقلید",
        "استهبان",
        "بوانات",
        "خرامه",
        "خنج",
        "سپیدان",
        "فراشبند",
        "قیر و کارزین",
        "کوار",
        "گراش",
        "ممسنی",
        "نی‌ریز",
        "ارژن",
        "ایج",
        "بابانار",
        "حاجی‌آباد",
        "زرقان",
        "سروستان",
        "شهرصدرا",
        "صفاشهر",
        "کره‌ای",
        "مهر",
    ],
    "قزوین": [
        "قزوین",
        "تاکستان",
        "الوند",
        "آبیک",
        "اقبالیه",
        "محمودآباد نمونه",
        "محمدیه",
        "بویین‌زهرا",
        "ارداق",
        "اسفرورین",
        "شال",
        "ضیاءآباد",
        "کوهین",
        "نرجه",
        "خرمدشت",
        "سگزآباد",
        "سیردان",
        "شریفیه",
        "معلم‌کلایه",
    ],
    "قم": [
        "قم",
        "جعفریه",
        "کهک",
        "قنوات",
        "سلفچگان",
        "دستجرد",
        "سعدآباد",
        "نوفل‌لوشاتو",
        "قاهان",
        "کرجندان",
    ],
    "کردستان": [
        "سنندج",
        "سقز",
        "مریوان",
        "بانه",
        "کامیاران",
        "قروه",
        "دیواندره",
        "بیجار",
        "دهگلان",
        "سروآباد",
        "چناره",
        "زرینه",
        "شویشه",
        "گروه",
        "یاسوکند",
        "آرمرده",
        "بلبان‌آباد",
        "بوالحسن",
        "توپ آغاج",
        "دزج",
        "دلبران",
        "سریش‌آباد",
        "شوی",
        "قصلان",
        "کانی سور",
        "موچش",
    ],
    "کرمان": [
        "کرمان",
        "سیرجان",
        "رفسنجان",
        "جیرفت",
        "بم",
        "زرند",
        "کهنوج",
        "شهر بابک",
        "انار",
        "بافت",
        "بردسیر",
        "رابر",
        "راور",
        "ریگان",
        "منوجان",
        "نرماشیر",
        "فهرج",
        "قلعه‌گنج",
        "کوهبنان",
        "گلباف",
        "ماهان",
        "پاریز",
        "چترود",
        "خانوک",
        "درب بهشت",
        "زیدآباد",
        "نگار",
    ],
    "کرمانشاه": [
        "کرمانشاه",
        "اسلام‌آباد غرب",
        "هرسین",
        "کنگاور",
        "جوانرود",
        "سنقر",
        "پاوه",
        "صحنه",
        "روانسر",
        "ثلاث باباجانی",
        "دالاهو",
        "روانسر",
        "سرپل ذهاب",
        "قصر شیرین",
        "گیلانغرب",
        "نودشه",
        "نوسود",
        "ازگله",
        "باینگان",
        "تازه‌آباد",
        "ماهیدشت",
        "میان راهان",
        "هلشی",
    ],
    "کهگیلویه و بویراحمد": [
        "یاسوج",
        "دوگنبدان",
        "دهدشت",
        "لیکک",
        "چرام",
        "لنده",
        "باشت",
        "پاتاوه",
        "چیتاب",
        "سوق",
        "گراب سفلی",
        "مادوان",
        "مارگون",
    ],
    "گلستان": [
        "گرگان",
        "گنبد کاووس",
        "علی‌آباد کتول",
        "بندر ترکمن",
        "آق‌قلا",
        "کردکوی",
        "بندر گز",
        "مینودشت",
        "آزادشهر",
        "رامیان",
        "کلاله",
        "گالیکش",
        "مراوه‌تپه",
        "نوکنده",
        "اینچه برون",
        "جلین",
        "دلند",
        "سنگدوین",
        "فاضل‌آباد",
        "مزرعه",
        "نظام‌آباد",
    ],
    "گیلان": [
        "رشت",
        "بندر انزلی",
        "لاهیجان",
        "لنگرود",
        "آستارا",
        "صومعه‌سرا",
        "رودسر",
        "فومن",
        "ماسال",
        "آستانه اشرفیه",
        "رودبار",
        "شفت",
        "سیاهکل",
        "اطاقور",
        "اسالم",
        "بندر کیاشهر",
        "پره سر",
        "چابکسر",
        "حویق",
        "خشکبیجار",
        "رضوانشهر",
        "سنگر",
        "شلمان",
        "کومله",
        "لشت نشا",
        "لولمان",
        "مرجقل",
    ],
    "لرستان": [
        "خرم‌آباد",
        "بروجرد",
        "دورود",
        "کوهدشت",
        "الیگودرز",
        "نورآباد",
        "ازنا",
        "الشتر",
        "پلدختر",
        "سپیددشت",
        "معمولان",
        "مومن‌آباد",
        "ویسیان",
        "چغلوندی",
        "چقابل",
        "زاغه",
        "سراب دوره",
        "فیروزآباد",
        "کوهنانی",
        "هفت‌چشمه",
    ],
    "مازندران": [
        "ساری",
        "بابل",
        "آمل",
        "قائم‌شهر",
        "بهشهر",
        "چالوس",
        "نکا",
        "بابلسر",
        "نوشهر",
        "رامسر",
        "تنکابن",
        "جویبار",
        "فریدونکنار",
        "محمودآباد",
        "عباس‌آباد",
        "گلوگاه",
        "کجور",
        "مرزن‌آباد",
        "نور",
        "پل سفید",
        "پول",
        "کلاردشت",
        "هچیرود",
        "امیرکلا",
        "شیرگاه",
        "کتالم",
    ],
    "مرکزی": [
        "اراک",
        "ساوه",
        "خمین",
        "محلات",
        "دلیجان",
        "تفرش",
        "آشتیان",
        "شازند",
        "زرندیه",
        "فراهان",
        "کمیجان",
        "خنداب",
        "مامونیه",
        "نوبران",
        "نیمور",
        "هندودر",
        "آوه",
        "پرندک",
        "جاورسیان",
        "خسروبیک",
        "داودآباد",
        "سنجان",
        "غرق‌آباد",
        "کارچان",
    ],
    "هرمزگان": [
        "بندرعباس",
        "میناب",
        "دهبارز",
        "بندر لنگه",
        "قشم",
        "کیش",
        "حاجی‌آباد",
        "بستک",
        "جاسک",
        "حاجی‌آباد",
        "خمیر",
        "رودان",
        "سیریک",
        "فین",
        "قشم",
        "گاوبندی",
        "پارسیان",
        "تخت",
        "جناح",
        "درگهان",
        "سوزا",
        "کوهستک",
        "لمزان",
        "هشتبندی",
    ],
    "همدان": [
        "همدان",
        "ملایر",
        "نهاوند",
        "تویسرکان",
        "اسدآباد",
        "کبودرآهنگ",
        "بهار",
        "رزن",
        "فامنین",
        "قروه درجزین",
        "آجین",
        "برزول",
        "جورقان",
        "دمق",
        "شراء",
        "صالح‌آباد",
        "فرسفج",
        "قلقلرود",
        "گیان",
        "لالجین",
        "مریانج",
        "مهاجران",
    ],
    "یزد": [
        "یزد",
        "میبد",
        "اردکان",
        "بافق",
        "مهریز",
        "ابرکوه",
        "تفت",
        "هرات",
        "اشکذر",
        "بهاباد",
        "حمیدیا",
        "زارچ",
        "شاهدیه",
        "عقدا",
        "مروست",
        "ندوشن",
        "نیر",
    ],
}

CommitteeMembersData = [
    {
        "Name": "دکتر بهروز مینایی بیدگلی",
        "Role": "رئیس مسابقات",
        "Description": "رهبری کلی مسابقات و نظارت بر اجرای صحیح تمامی مراحل برگزاری",
        "Image": "Images/Committee/Minayi.png",
    },
    {
        "Name": "دکتر داوود زارع",
        "Role": "رئیس کمیته ملی مسابقات",
        "Description": "هماهنگی و نظارت بر کلیه فعالیت‌های کمیته‌های تخصصی",
        "Image": "Images/Committee/Davood.png",
    },
    {
        "Name": "مهندس زهرا سعادتی داریان",
        "Role": "دبیر کمیته علمی",
        "Description": "مسئولیت ارزیابی علمی پروژه‌ها و تنظیم معیارهای داوری",
        "Image": "Images/Committee/Saadati.png",
    },
    {
        "Name": "مهندس محمدرضا ریاحی سامانی",
        "Role": "دبیر کمیته رباتیک",
        "Description": "مسئولیت برگزاری لیگ‌های رباتیک و ارزیابی ربات‌ها",
        "Image": "Images/Committee/Riyahi.png",
    },
    {
        "Name": "مهندس پوریا حداد",
        "Role": "دبیر کمیته هوش مصنوعی",
        "Description": "مسئولیت برگزاری لیگ‌های هوش مصنوعی و ارزیابی پروژه‌ها",
        "Image": "Images/Committee/Poria.png",
    },
    {
        "Name": "دکتر محمد خلیل پور",
        "Role": "دبیر کمیته پشتیبانی",
        "Description": "مسئولیت پشتیبانی فنی و حل مشکلات شرکت‌کنندگان",
        "Image": "Images/Committee/Khalil Pore.png",
    },
]

TechnicalCommitteeMembersData = [
    {
        "Name": "دکتر سمیه سلطانی",
        "Role": "رئیس لیگ کاربرد هوش مصنوعی در علوم پزشکی و بهداشت",
        "Description": "استاد دانشگاه تبریز",
        "Image": "Images/Technical Committee/Somaieh Soltani.png",
    },
    {
        "Name": "مهندس امیر حسین کرمی",
        "Role": "مدیر امور استان ها",
        "Description": "هماهنگی٬ برنامه ریزی و پیگیری امور استان ها",
        "Image": "Images/Technical Committee/Amir Hossain.png",
    },
]

LeaguesListData = [
    {
        "ID": 1,
        "Name": "لیگ آیروچلنج حل چالش‌ها با ربات و هوش مصنوعی",
        "Icon": "fa-puzzle-piece",
        "Description": "لیگ آیروچلنج، نقطه‌ی تلاقی خلاقیت، مهارت فنی و تفکر حل‌مسئله است. در این رقابت، شرکت‌کنندگان با طراحی ربات‌ها یا الگوریتم‌های هوشمند، مأموریت‌های واقعی را در زمینه‌های گوناگون مانند نجات، حمل‌ونقل یا محیط‌زیست حل می‌کنند. این لیگ ترکیبی از نوآوری مهندسی و هوش مصنوعی است و بستری برای سنجش توانایی تیم‌ها در طراحی، پیاده‌سازی و تحلیل سیستم‌های هوشمند فراهم می‌آورد.",
    },
    {
        "ID": 2,
        "Name": "لیگ تولید محتوای دیجیتال ویژه بازار کار",
        "Icon": "fa-solid fa-compass-drafting",
        "Description": "این لیگ با هدف پرورش خلاقیت دیجیتال و مهارت‌های تولید محتوای کاربردی طراحی شده است. شرکت‌کنندگان در سه سطح (ابتدایی، متوسطه و دانشجویی) با استفاده از ابزارهای حرفه‌ای و هوش مصنوعی، محتوای آموزشی، تبلیغاتی یا فرهنگی تولید می‌کنند. داوری بر اساس خلاقیت، کیفیت فنی، تلفیق AI و کاربردی بودن آثار انجام می‌شود. هدف نهایی، آماده‌سازی نسل جوان برای حضور مؤثر در بازار کار دیجیتال است.",
    },
    {
        "ID": 3,
        "Name": "لیگ تولید محتوا با هوش مصنوعی",
        "Icon": "fa-solid fa-video",
        "Description": "در این لیگ، تمرکز بر تولید ویدئو یا پوسترهای خلاقانه با بهره‌گیری از ابزارهای هوش مصنوعی است. شرکت‌کنندگان می‌توانند در دو بخش مستقل رقابت دهند: تولید محتوای ویدیویی و طراحی پوستر تبلیغاتی. این رقابت بستری است برای نمایش قدرت خلاقیت، مهارت فنی و درک هنری در استفاده از فناوری‌های مولد (Generative AI) برای انتقال پیام‌های آموزشی، فرهنگی یا تجاری.",
    },
    {
        "ID": 4,
        "Name": "لیگ ساخت عامل هوشمند (AI Agent)",
        "Icon": "fa-brain",
        "Description": "در این لیگ، شرکت‌کنندگان به طراحی و توسعه‌ی عامل‌های هوشمند می‌پردازند؛ سیستم‌هایی که می‌توانند به‌صورت خودکار تصمیم بگیرند، تحلیل کنند و با کاربر یا محیط تعامل داشته باشند. این عامل‌ها می‌توانند در قالب چت‌بات، دستیار مجازی یا سیستم‌های تصمیم‌یار طراحی شوند. داوری بر اساس خلاقیت، کارایی، تعامل کاربری و قابلیت توسعه انجام می‌گیرد.",
    },
    {
        "ID": 5,
        "Name": "لیگ اختراعات رباتیک و هوش مصنوعی",
        "Icon": "fa-lightbulb",
        "Description": "این لیگ ترکیبی از پژوهش، نوآوری و کارآفرینی فناورانه است. شرکت‌کنندگان در سه بخش «محصول»، «ایده» و «پژوهش» رقابت می‌کنند و باید توانایی خود را در ارائه طرح‌های فناورانه، مدل‌های تجاری‌سازی و مستندات علمی نشان دهند. هدف اصلی، تبدیل ایده‌های پژوهشی به محصولات واقعی و ایجاد پیوند میان علم، صنعت و نوآوری است.",
    },
    {
        "ID": 6,
        "Name": "لیگ جنگجوهای هوشمند",
        "Icon": "fa-shield-alt",
        "Description": "در این لیگ هیجان‌انگیز، شرکت‌کنندگان ربات‌هایی طراحی می‌کنند که در زمین مسابقه با رعایت اصول ایمنی با یکدیگر رقابت می‌کنند. هدف اصلی، آموزش اصول طراحی مکانیکی، کنترل هوشمند و تحلیل استراتژیک است. داوری بر اساس عملکرد، استراتژی، ایمنی و نوآوری انجام می‌شود. این لیگ برای هر دو سطح دانش‌آموزی و دانشجویی قابل شرکت است.",
    },
    {
        "ID": 7,
        "Name": "لیگ برنامه‌نویسی و هوش مصنوعی",
        "Icon": "fa-code",
        "Description": "این لیگ برای علاقه‌مندان به کدنویسی و حل مسائل پیچیده طراحی شده است. مسابقه در چهار بخش برگزار می‌شود: اسکرچ، ACM، پایتون و هوش مصنوعی. شرکت‌کنندگان از مفاهیم پایه تا مباحث پیشرفته الگوریتمی، به رقابت در بهینه‌سازی کد، دقت و خلاقیت در طراحی راه‌حل می‌پردازند. این لیگ فرصتی برای شناسایی استعدادهای برتر در حوزه برنامه‌نویسی هوشمند است.",
    },
    {
        "ID": 8,
        "Name": "لیگ نمایش ربات‌ها",
        "Icon": "fa-star",
        "Description": "در این لیگ، ربات‌ها نه برای مبارزه بلکه برای نمایش خلاقیت، طراحی و تعامل با انسان ساخته می‌شوند. تیم‌ها ربات‌هایی را طراحی می‌کنند که بتوانند حرکات نمایشی، رفتارهای تعاملی یا عملکردهای هنری از خود نشان دهند. ارزیابی بر اساس نوآوری، جذابیت بصری، کیفیت ارائه و ایمنی انجام می‌شود. این لیگ ترکیبی از فناوری، هنر و ارتباط با مخاطب است.",
    },
    {
        "ID": 9,
        "Name": "لیگ ربات امدادگر محیط‌زیست",
        "Icon": "fa-leaf",
        "Description": "در این رقابت، ربات‌ها مأموریت دارند تا در سناریوهای امدادی و زیست‌محیطی فعالیت کنند؛ از شناسایی آلودگی تا جمع‌آوری پسماند یا نجات در شرایط بحرانی. شرکت‌کنندگان باید ربات‌هایی بسازند که بتوانند به‌صورت خودمختار داده‌ها را تحلیل و بهترین تصمیم را اتخاذ کنند. این لیگ تلفیقی از علم، فناوری و مسئولیت اجتماعی است.",
    },
    {
        "ID": 10,
        "Name": "لیگ ربات پرنده",
        "Icon": "fa-solid fa-plane",
        "Description": "این لیگ برای علاقه‌مندان به طراحی پهپادها و سیستم‌های پروازی هوشمند طراحی شده است. تیم‌ها باید ربات‌های پرنده‌ای بسازند که توانایی انجام مأموریت‌های خاص مانند حمل بار، فیلم‌برداری یا نقشه‌برداری خودکار را داشته باشند. ارزیابی بر اساس پایداری پرواز، دقت کنترل، ایمنی و نوآوری در طراحی انجام می‌شود.",
    },
    {
        "ID": 11,
        "Name": "لیگ خودرو خودران",
        "Icon": "fa-solid fa-car",
        "Description": "در این لیگ، شرکت‌کنندگان باید یک خودروی هوشمند طراحی کنند که بتواند در مسیر مشخص، موانع را شناسایی کرده و به‌صورت خودکار حرکت کند. محورهای اصلی شامل بینایی ماشین، کنترل خودکار و تصمیم‌گیری هوشمند است. این لیگ مقدمه‌ای برای ورود به دنیای وسایل نقلیه خودران و فناوری‌های آینده‌ی حمل‌ونقل است.",
    },
    {
        "ID": 12,
        "Name": "لیگ کشاورز هوشمند (AgriTech AI)",
        "Icon": "fa-solid fa-tractor",
        "Description": "هدف این لیگ، پرورش مهارت‌های هوش مصنوعی در حوزه‌ی کشاورزی است. شرکت‌کنندگان با طراحی الگوریتم‌ها و عامل‌های هوشمند در محیط شبیه‌سازی‌شده، به بهینه‌سازی مصرف آب، کود، بذر و انرژی می‌پردازند. داوری بر اساس دقت تشخیص، بهره‌وری منابع و عملکرد کلی انجام می‌شود. این رقابت بستری برای توسعه فناوری‌های AgriTech در ایران است.",
    },
    {
        "ID": 13,
        "Name": "لیگ هوش مصنوعی در علوم پزشکی و سلامت (Medi AI)",
        "Icon": "fa-stethoscope",
        "Description": "در این لیگ، تیم‌ها راهکارهای مبتنی بر هوش مصنوعی برای تحلیل داده‌های پزشکی، تشخیص بیماری‌ها، پایش سلامت و تصمیم‌یارهای بالینی توسعه می‌دهند. هدف، آموزش کاربردهای علمی و اخلاقی هوش مصنوعی در پزشکی است. داوری بر اساس دقت مدل، نوآوری، قابلیت تفسیر و کاربردپذیری در نظام سلامت انجام می‌شود.",
    },
    {
        "ID": 14,
        "Name": "لیگ مدیریت هوشمند مصرف آب (Aqua AI)",
        "Icon": "fa-tint",
        "Description": "با توجه به بحران آب در ایران، این لیگ با هدف آموزش هوش مصنوعی در مدیریت منابع آبی طراحی شده است. در دو سطح دانش‌آموزی و دانشجویی، شرکت‌کنندگان با داده‌های واقعی کار کرده و مدل‌هایی برای پیش‌بینی مصرف، تشخیص نشتی و بهینه‌سازی شبکه‌های آبرسانی طراحی می‌کنند. این لیگ نمونه‌ای از کاربرد مستقیم علم داده و AI در حل چالش‌های ملی است.",
    },
]

GlobalHTMLNamesData = {
    "About": "Global/About.html",
    "Base": "Global/Base.html",
    "Committee": "Global/Committee.html",
    "TechnicalCommittee": "Global/TechnicalCommittee.html",
    "Contact": "Global/Contact.html",
    "Cooperate": "Global/Cooperate.html",
    "Gallery": "Global/Gallery.html",
    "Index": "Global/Index.html",
    "Leagues": "Global/Leagues.html",
    "News": "Global/News.html",
    "Sponsors": "Global/Sponsors.html",
    "404": "Global/404.html",
    "500": "Global/500.html",
    "400": "Global/400.html",
    "403": "Global/403.html",
    "500 Debug": "Global/500Debug.html",
    "Article": "Global/Article.html",
}

ClientHTMLNamesData = {
    "CreateTeam": "Client/CreateTeam.html",
    "Dashboard": "Client/Dashboard.html",
    "ForgotPassword": "Client/ForgotPassword.html",
    "Login": "Client/Login.html",
    "MemberFormFields": "Client/MemberFormFields.html",
    "Members": "Client/Members.html",
    "Payment": "Client/Payment.html",
    "ResetPassword": "Client/ResetPassword.html",
    "SelectLeague": "Client/SelectLeague.html",
    "SignUp": "Client/SignUp.html",
    "Null": "Client/Null.html",
    "SupportChat": "Client/SupportChat.html",
    "UpdateTeam": "Client/UpdateTeam.html",
    "Verify": "Client/Verify.html",
    "EditMember": "Client/EditMember.html",
    "MyHistory": "Client/MyHistory.html",
}

AdminHTMLNamesData = {
    "AdminChat": "Admin/AdminChat.html",
    "AdminChatList": "Admin/AdminChatList.html",
    "AdminClientsList": "Admin/AdminClientsList.html",
    "AdminDashboard": "Admin/AdminDashboard.html",
    "AdminEditNews": "Admin/AdminEditNews.html",
    "AdminEditTeam": "Admin/AdminEditTeam.html",
    "AdminLogin": "Admin/AdminLogin.html",
    "AdminManageClient": "Admin/AdminManageClient.html",
    "AdminManageNews": "Admin/AdminManageNews.html",
    "AdminManageTeams": "Admin/AdminManageTeams.html",
    "AdminAddMember": "Admin/AdminAddMember.html",
}

CooperationOpportunitiesData = [
    {
        "icon": "fas fa-handshake",
        "title": "حمایت و اسپانسرشیپ",
        "description": "نام تجاری خود را در قلب بزرگترین رویداد هوش مصنوعی کشور به نمایش بگذارید و تعهد سازمان خود به نوآوری و پیشرفت فناوری را نشان دهید.",
    },
    {
        "icon": "fas fa-brain",
        "title": "تعریف چالش‌های صنعتی",
        "description": "مسائل واقعی صنعت خود را از طریق نوآوری باز حل کنید. چالش‌های سازمان خود را به یک رقابت هیجان‌انگیز برای صدها تیم خلاق تبدیل کنید.",
    },
    {
        "icon": "fas fa-chalkboard-teacher",
        "title": "همکاری علمی و داوری",
        "description": "دانش و تجربه خود را با نسل آینده به اشتراک بگذارید. از اساتید و متخصصان برجسته برای ارتقای سطح علمی رویداد دعوت به همکاری می‌کنیم.",
    },
    {
        "icon": "fas fa-users-cog",
        "title": "پیوستن به تیم اجرایی",
        "description": "اگر فردی پرانرژی و علاقه‌مند به دنیای فناوری هستید، به تیم اجرایی آیروکاپ بپیوندید و تجربه‌ای بی‌نظیر در برگزاری یک رویداد ملی کسب کنید.",
    },
    {
        "icon": "fas fa-trophy",
        "title": "برگزاری لیگ‌های تخصصی",
        "description": "تخصص و حوزه فعالیت خود را به یک لیگ رقابتی تبدیل کنید. ما بستر لازم برای افزودن رقابت‌های جدید به آیروکاپ را فراهم می‌کنیم.",
    },
    {
        "icon": "fas fa-box-open",
        "title": "همکاری در تامین تجهیزات",
        "description": "آیروکاپ به قطعات الکترونیکی، رباتیک و نرم‌افزار نیاز دارد. از شرکت‌های واردکننده و تامین‌کننده دعوت می‌کنیم تا با ارائه محصولات خود، به عنوان شریک فنی در کنار ما باشند.",
    },
    {
        "icon": "fas fa-bullhorn",
        "title": "همکاری رسانه‌ای و تبلیغاتی",
        "description": "از رسانه‌ها، خبرگزاری‌ها و شرکت‌های تبلیغاتی دعوت می‌کنیم تا با پوشش خبری و اطلاع‌رسانی، به دیده‌شدن این رویداد ملی کمک کرده و برند خود را معرفی کنند.",
    },
    {
        "icon": "fas fa-university",
        "title": "مشارکت علمی و دانشگاهی",
        "description": "از دانشگاه‌ها، مراکز پژوهشی و موسسات آموزشی دعوت می‌شود تا به عنوان شریک علمی، در غنی‌سازی محتوای رویداد و تشویق دانشجویان به شرکت، با ما همراه شوند.",
    },
    {
        "icon": "fas fa-concierge-bell",
        "title": "ارائه خدمات و پشتیبانی",
        "description": "برگزاری یک رویداد بزرگ نیازمند خدمات اجرایی و پشتیبانی است. از ارائه‌دهندگان خدمات (لجستیک، پذیرایی، و...) برای همکاری در اجرای هرچه بهتر مسابقات دعوت می‌کنیم.",
    },
]

GalleryVideosData = [
    {
        "title": "علام برگزاری اولین دوره مسابقات هوش مصنوعی و رباتیک آیروکاپ",
        "src": "https://www.aparat.com/video/video/embed/videohash/tgg3hv0/vt/frame",
    },
    {
        "title": "آیروکاپ | مشاغل آینده دار برای نوجوانان",
        "src": "https://www.aparat.com/video/video/embed/videohash/ket93i2/vt/frame",
    },
    {
        "title": "آیروکاپ | آماده سازی نوجوانان برای دنیای رباتیک",
        "src": "https://www.aparat.com/video/video/embed/videohash/icpiigb/vt/frame",
    },
    {
        "title": "آیروکاپ | اهمیت دانش رباتیک و مهارت های نرم برای دانش آموزان",
        "src": "https://www.aparat.com/video/video/embed/videohash/pyv0uga/vt/frame",
    },
]

HomepageSponsorsData = [
    {"logo_key": "InteriorMinistry", "alt_text": "وزارت کشور جمهوری اسلامی ایران"},
    {"logo_key": "StudentResearchCenter", "alt_text": "پژوهش سرای دانش آموزی"},
    {"logo_key": "EducationMinistry", "alt_text": "وزارت آموزش و پرورش"},
    {"logo_key": "WaterWaste", "alt_text": "شرکت مهندسی آب و فاضلاب کشور"},
    {
        "logo_key": "EducationDepartmentTehran",
        "alt_text": "اداره کل آموزش و پرورش شهر تهران",
    },
    {
        "logo_key": "StudentResearchCenterTehran",
        "alt_text": "پژوهش سرای دانش آموزی تهران",
    },
]

EducationAgeRanges = {
    level: details["ages"]
    for level, details in EducationLevels.items()
    if details["ages"]
}

Weekdays = {
    "Saturday": "شنبه",
    "Sunday": "یکشنبه",
    "Monday": "دوشنبه",
    "Tuesday": "سه‌شنبه",
    "Wednesday": "چهارشنبه",
    "Thursday": "پنجشنبه",
    "Friday": "جمعه",
}
